Kyanime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anime.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    path('contact/', include('contact.urls')),
    path('accounts/', include('allauth.urls')),
    path('oauth/', include('social_django.urls', namespace='social'))

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Kyanime"
admin.site.index_title = "Panel de Administrador"
admin.site.site_title = "Kyanime, tu página"

anime/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.anime, name='anime'),
    path('galeria/', views.galeria, name='galeria'),
    path('anime/<str:pk>', views.AnimeDetailView.as_view(), name='anime-detail'),
    path('galeria/<str:pk>', views.GaleriaDetailView.as_view(),
         name='galeria-detail'),
]
urlpatterns += [
    path('anime/create/', views.AnimeCreate.as_view(), name='anime_create'),
    path('anime/<str:pk>/update', views.AnimeUpdate.as_view(), name='anime_update'),
    path('anime/<str:pk>/delete', views.AnimeDelete.as_view(), name='anime_delete'),
    path('galeria/create/', views.GaleriaCreate.as_view(), name='galeria_create'),
    path('galeria/<str:pk>/update',
         views.GaleriaUpdate.as_view(), name='galeria_update'),
    path('galeria/<str:pk>/delete',
         views.GaleriaDelete.as_view(), name='galeria_delete')
]

anime/models.py
from django.db import models
from django.urls import reverse
import uuid


class Galeria(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4,  editable=False)
    nombre_anime = models.CharField(max_length=200)
    descripcion = models.TextField(max_length=1000)
    imagen = models.ImageField(
        upload_to='galeria/', null=True, blank=True)

    class Meta:
        ordering = ['nombre_anime']

    def __str__(self):
        return self.nombre_anime

    def get_absolute_url(self):
        """Devuelve la url para acceder a un registro detallado de el Anime."""
        return reverse('galeria-detail', args=[str(self.id)])


class Anime(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4,  editable=False)
    nombre_anime = models.CharField(max_length=200)
    episodios = models.IntegerField(default=0)
    sinopsis = models.TextField(max_length=1000)
    imagen = models.ImageField(
        upload_to='anime/', null=True, blank=True)
    opening = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        ordering = ['nombre_anime']

    def __str__(self):
        """String for representing the Model object."""
        return self.nombre_anime

    def get_absolute_url(self):
        return reverse('anime-detail', args=[str(self.id)])

anime/forms.py
from django import forms

from . models import Galeria, Anime


class AnimeForm(forms.ModelForm):
    nombre_anime = forms.CharField(label='Nombre Anime', max_length=200, widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    ))
    episodios = forms.IntegerField(label='Episodios', widget=forms.NumberInput(
        attrs={
            'class': 'form-control'
        }
    ))
    sinopsis = forms.CharField(label='Descripción', max_length=1000, widget=forms.Textarea(
        attrs={
            'class': 'form-control'
        }
    ))

    class Meta:
        model = Anime
        fields = ('nombre_anime', 'episodios', 'sinopsis')


class GaleriaForm(forms.ModelForm):
    nombre_anime = forms.CharField(label='Nombre Anime', max_length=200, widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    ))
    descripcion = forms.CharField(label='Descripción', max_length=1000, widget=forms.Textarea(
        attrs={
            'class': 'form-control'
        }
    ))
    imagen = forms.ImageField(label='Imagen',
                              widget=forms.ClearableFileInput(
                                  attrs={
                                      'class': 'form-control'
                                  }
                              ))

    class Meta:
        model = Galeria
        fields = ('nombre_anime', 'descripcion', 'imagen')
        widgets = {'id': forms.HiddenInput()}

anime/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect, get_object_or_404
from . models import Galeria, Anime
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.views import generic
from django.shortcuts import redirect
from . forms import AnimeForm, GaleriaForm


# Create your views here.
# objects.all() es como un select * from
# objects.filter es como un where


class StaffRequiredMixin(object):
    @method_decorator(staff_member_required)
    def dispatch(self, request, *args, **kwargs):
        return super(StaffRequiredMixin, self).dispatch(request, *args, **kwargs)


def anime(request):
    num_animes = Anime.objects.all()

    return render(
        request,
        'anime.html',
        context={'num_animes':  num_animes}
    )


def galeria(request):
    num_fotos = Galeria.objects.all()

    return render(
        request,
        'galeria.html',
        context={'num_fotos':  num_fotos}
    )


def login(request):

    return render(
        request,
        'login.html',
    )


def register(request):

    return render(
        request,
        'register.html',
    )


@method_decorator(staff_member_required, name='dispatch')
class AnimeCreate(CreateView):
    model = Anime
    fields = '__all__'


@method_decorator(staff_member_required, name='dispatch')
class AnimeUpdate(UpdateView):
    model = Anime
    fields = '__all__'


@method_decorator(staff_member_required, name='dispatch')
class AnimeDelete(DeleteView):
    model = Anime
    success_url = reverse_lazy('anime')


class AnimeDetailView(generic.DetailView):
    model = Anime


class AnimeListView(generic.ListView):
    model = Anime


class GaleriaCreate(CreateView):
    model = Galeria
    fields = '__all__'


class GaleriaUpdate(UpdateView):
    model = Galeria
    fields = '__all__'


class GaleriaDelete(DeleteView):
    model = Galeria
    success_url = reverse_lazy('galeria')


class GaleriaDetailView(generic.DetailView):
    model = Galeria


def anime_new(request):
    if request.method == "POST":
        form = AnimeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('anime-detail', pk=post.pk)
    else:
        form = AnimeForm()
        return render(request, 'anime/anime_form.html', {'form': form})


def anime_edit(request, pk):
    post = get_object_or_404(Anime, pk=pk)
    if request.method == "POST":
        form = AnimeForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('anime-detail', pk=post.pk)
    else:
        form = AnimeForm(instance=post)
    return render(request, 'anime/anime_form.html', {'form': form})


def galeria_new(request):
    if request.method == "POST":
        form = GaleriaForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('galeria-detail', pk=post.pk)
    else:
        form = GaleriaForm()
        return render(request, 'anime/galeria_form.html', {'form': form})


def galeria_edit(request, pk):
    post = get_object_or_404(Galeria, pk=pk)
    if request.method == "POST":
        form = GaleriaForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            post.save()
            return redirect('galeria-detail', pk=post.pk)
    else:
        form = GaleriaForm(instance=post)
    return render(request, 'anime/galeria_form.html', {'form': form})

anime/templates/anime/anime_confirm_delete.html
{% extends "base_generic.html" %} {% block content %} {% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
   <title>Kyanime - ¿Eliminar?</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href=" {% static 'css/estilos.css' %}" />
  </head>
  <body>
    <div class="container-bg pt-5 pb-5">
      <div class="container bg-white">
        <div class="pt-4 text-center">
          <h1>Estás seguro de borrar el Anime?</h1>
          <br />
          <img
            src="{{anime.imagen.url}}"
            class="img-rounded img-fluid"
            alt="{{anime.nombre_anime}}"
          />
          <h1>Anime: {{anime.nombre_anime}}</h1>
          <form action="" method="POST">
            {% csrf_token %}

            <a
              href="{% url 'anime-detail' anime.pk %}"
              class="btn btn-anime btn-xl"
              style="float: left"
              >Atras</a
            >
            <button
              type="submit"
              class="save btn btn-anime btn-xl"
              style="float: right"
            >
              Borrar
            </button>
          </form>
        </div>
        <br /><br />
      </div>
    </div>
  </body>
</html>
{% endblock %}

anime/templates/anime/anime_detail.html
{% extends "base_generic.html" %} {% block content %} {% load static %}

<html lang="en">
  <head>
   <title>Kyanime - {{anime.nombre_anime}}</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href=" {% static 'css/estilos.css' %}" />
  </head>
  <body>
    <div class="container-bg pt-5 pb-5">
      <div class="container bg-white">
        <div class="pt-4 text-center">
          <img
            src="{{anime.imagen.url}}"
            class="img-rounded img-fluid"
            alt="{{anime.nombre_anime}}"
          />
          <h1 style="font-weight: bold;">{{anime.nombre_anime}}</h1>
          <p>{{anime.sinopsis}}</p>
          <p><span style="color:#ff6720; font-weight: bold;">Episodios:</span> {{ anime.episodios }}</p>

          
          {% if  anime.opening %}     
                            
              <p style="font-weight: bold; font-size: 18px;">Opening</p>
              
                <div class="row link" link-video="{{anime.opening}}">                
                  <div class="col-sm-3"></div>
                  <div class="col-sm-6 pb-3">
                    <div class="embed-responsive embed-responsive-16by9">                     
                      <iframe id="iframe-datail" src=""
                        allowfullscreen ></iframe>                      
                      </p>                     
                    </div>                    
                  </div>
                </div>
          {% endif %}

          <a
            href="{% url 'anime' %}"
            class="btn btn-anime"
            style="float: left"
          >
            Atrás
          </a>
          <a
            href="{% url 'anime_update' pk=anime.pk %}"
            class="btn btn-anime"
            style="float: center"
          >
            Editar
          </a>
          <a
            href="{% url 'anime_delete' pk=anime.pk %}"
            class="btn btn-anime"
            style="float: right"
          >
            Eliminar
          </a>
        </div>
        <br />
      </div>
    </div>
    <script src="{% static 'js/jquery-3.5.1.min.js' %} "></script>
                <script>
  videoLink();
  function videoLink(){
    var video=$('.link').attr('link-video');
    var arrayVideo = video.split('=');
    $('#iframe-datail').attr('src',"https://www.youtube.com/embed/"+arrayVideo[1]+"?modestbranding=1&showinfo=0");    
  }
  </script>
  </body>

</html>

{% endblock %}

anime/templates/anime/anime_form.html
{% extends "base_generic.html" %} {% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
  <title>Kyanime - Añadir Anime</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href=" {% static 'css/estilos.css' %}" />
  </head>
  <body>
    <div class="container-bg text-white pt-4">
      <div class="container">
        <br /><br />
        <h2 class="page-section-heading text-center">
          Añadir Anime
        </h2>

        <div class="row pb-4 pt-4">
          <div class="col-md-4 col-sm-6 col-lg-4 col-xl-4 mx-auto">
            <form method="POST" class="post-form" enctype="multipart/form-data">
              {% csrf_token %}

              <div class="col-md-6 col-6">{{ form.as_p }}</div>

              <button
                type="submit"
                class="save btn btn-anime"
                style="float: right"
              >
                Guardar
              </button>
              <button
                onClick="javascript:history.go(-1)"
                class="btn btn-anime"
                style="float: left"
              >
                Atrás
              </button>
            </form>
            <br />
            <br />
          </div>
        </div>
      </div>
    </div>
      <script src="{% static 'js/jquery-3.5.1.min.js' %} "></script>
                
    <script>
    inputs();
    function inputs(){
      $('#id_nombre_anime').addClass('form-control');
      $('#id_nombre_anime').css({"width":"300px"});
      $('#id_episodios').css({"width":"300px"});
      $('#id_sinopsis').css({"width":"300px"});
      $('#id_opening').css({"width":"300px"});
      $('#id_episodios').addClass('form-control');
      $('#id_sinopsis').addClass('form-control');
      $('#id_opening').addClass('form-control');

    }
    </script>
  </body>
</html>

{% endblock %}

anime/templates/anime/anime_list.html
{% extends "base_generic.html" %} {% block content %}
<h1>Lista de Anime</h1>

{% if anime_list %}

<ul>
  {% for anime in anime_list %}
  <li>
    <a href="{{ anime.get_absolute_url }}"> {{ anime.nombre_anime }} </a>
  </li>
  {% endfor %}
</ul>

{% else %}
<p>No se ha agregado ningún Anime</p>

{% endif %} {% endblock %}

anime/templates/anime/galeria_confirm_delete.html
{% extends "base_generic.html" %} {% block content %} {% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
  <title>Kyanime - ¿Eliminar?</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href=" {% static 'css/estilos.css' %}" />
  </head>
  <body>
    <div class="container-bg pt-5 pb-5">
      <div class="container bg-white">
        <div class="pt-4 text-center">
          <h1>Estás seguro de borrar la Imagen?</h1>
          <br />
          <img
            src="{{galeria.imagen.url}}"
            class="img-rounded img-fluid"
            alt="{{galeria.nombre_anime}}"
          />
          <h1>Anime: {{galeria.nombre_anime}}</h1>
          <form action="" method="POST">
            {% csrf_token %}

            <a
              href="{% url 'galeria-detail' galeria.pk %}"
              class="btn btn-anime btn-xl"
              style="float: left"
              >Atras</a
            >
            <button
              type="submit"
              class="save btn btn-anime btn-xl"
              style="float: right"
            >
              Borrar
            </button>
          </form>
        </div>
        <br /><br />
      </div>
    </div>
  </body>
</html>
{% endblock %}

anime/templates/anime/galeria_detail.html
{% extends "base_generic.html" %} {% block content %} {% load static %}

<html lang="en">
  <head>
  <title>Kyanime - {{galeria.nombre_anime}}</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href=" {% static 'css/estilos.css' %}" />
  </head>
  <body>
    <div class="container-bg pt-5 pb-5">
      <div class="container bg-white">
        <div class="pt-4 text-center">
          <img
            src="{{galeria.imagen.url}}"
            class="img-rounded img-fluid"
            alt="{{galeria.nombre_anime}}"
          />
          <h1>{{galeria.nombre_anime}}</h1>
          <p>{{galeria.descripcion}}</p>
          <a
            href="{% url 'galeria' %}"
            class="btn btn-anime"
            style="float: left"
          >
            Atrás
          </a>
          <a
            href="{% url 'galeria_update' pk=galeria.pk %}"
            class="btn btn-anime"
            style="float: center"
          >
            Editar
          </a>
          <a
            href="{% url 'galeria_delete' pk=galeria.pk %}"
            class="btn btn-anime"
            style="float: right"
          >
            Eliminar
          </a>
        </div>
        <br />
      </div>
    </div>
  </body>
</html>

{% endblock %}

anime/templates/anime/galeria_form.html
{% extends "base_generic.html" %} {% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
  <title>Kyanime - Añadir Imagen</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href=" {% static 'css/estilos.css' %}" />
  </head>
  <body>
    <div class="container-bg text-white pt-4">
      <div class="container">
        <br /><br />
        <h2 class="page-section-heading text-center">
          Añadir Imágen a Galería
        </h2>

        <div class="row pb-4 pt-4">
          <div class="col-md-4 col-sm-6 col-lg-4 col-xl-4 mx-auto">
            <form method="POST" class="post-form" enctype="multipart/form-data">
              {% csrf_token %}

              <div class="col-md-6 col-6">{{ form.as_p }}</div>

              <button
                type="submit"
                class="save btn btn-anime"
                style="float: right"
              >
                Guardar
              </button>
              <button
                onClick="javascript:history.go(-1)"
                class="btn btn-anime"
                style="float: left"
              >
                Atrás
              </button>
            </form>
            <br />
            <br />
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

{% endblock %}

anime/templates/anime/galeria_list.html
{% extends "base_generic.html" %} {% block content %}
<h1>Lista de Imagenes</h1>

{% if galeria_list %}

<ul>
  {% for galeria in galeria_list %}
  <li>
    <a href="{{ galeria.get_absolute_url }}"> {{ galeria.nombre_anime }} </a>
  </li>
  {% endfor %}
</ul>

{% else %}
<p>No se ha agregado ninguna imagen</p>

{% endif %} {% endblock %}